import org.antlr.v4.runtime.tree.ParseTreeVisitor;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.CharStreams;
import java.io.IOException;

public class main {
    public static void main(String[] args) throws IOException{

	// we expect exactly one argument: the name of the input file
	if (args.length!=1) {
	    System.err.println("\n");
	    System.err.println("Impl Interpreter\n");
	    System.err.println("=================\n\n");
	    System.err.println("Please give as input argument a filename\n");
	    System.exit(-1);
	}
	String filename=args[0];

	// open the input file
	CharStream input = CharStreams.fromFileName(filename);
	    //new ANTLRFileStream (filename); // depricated
	
	// create a lexer/scanner
	implLexer lex = new implLexer(input);
	
	// get the stream of tokens from the scanner
	CommonTokenStream tokens = new CommonTokenStream(lex);
	
	// create a parser
	implParser parser = new implParser(tokens);
	
	// and parse anything from the grammar for "start"
	ParseTree parseTree = parser.start();

	// Construct an interpreter and run it on the parse tree
	Interpreter interpreter = new Interpreter();
	AST result = interpreter.visit(parseTree);
    }
}

// We write an interpreter that implements interface
// "implVisitor<T>" that is automatically generated by ANTLR
// This is parameterized over a return type "<T>" which is in our case
// simply a Double.

class Interpreter extends AbstractParseTreeVisitor<AST> implements implVisitor<AST> {
	@Override
	public AST visitStart(implParser.StartContext ctx) {
		return null;
	}

	@Override
	public AST visitSimInp(implParser.SimInpContext ctx) {
		return null;
	}

	@Override
	public AST visitLatches(implParser.LatchesContext ctx) {
		return null;
	}

	@Override
	public AST visitAssignment(implParser.AssignmentContext ctx) {
		return null;
	}

	@Override
	public AST visitNOT(implParser.NOTContext ctx) {
		return null;
	}

	@Override
	public AST visitOR(implParser.ORContext ctx) {
		return null;
	}

	@Override
	public AST visitAND(implParser.ANDContext ctx) {
		return null;
	}

	@Override
	public AST visitParentheses(implParser.ParenthesesContext ctx) {
		return null;
	}

	@Override
	public AST visitStringVar(implParser.StringVarContext ctx) {
		return null;
	}

/*
	@Override
	public AST visitStart(implParser.StartContext ctx) {
		return null;
	}

	@Override
	public AST visitSimInp(implParser.SimInpContext ctx) {
		return null;
	}

	@Override
	public AST visitLatches(implParser.LatchesContext ctx) {
		return null;
	}

	@Override
	public AST visitAssignment(implParser.AssignmentContext ctx) {
		return new Assignment(visit(ctx).toString(),(Expr)visit(ctx));
	}

	@Override
	public AST visitSequence(implParser.SequenceContext ctx) {
		return new Sequence((Command)visit(ctx.c),visit(ctx.cs));
	}

	@Override
	public AST visitNOT(implParser.NOTContext ctx) {
		return new NOT((Expr)visit(ctx.e1));
	}

	@Override
	public AST visitOR(implParser.ORContext ctx) {
		return new OR((Expr)visit(ctx.e1),(Expr)visit(ctx.e2));
	}

	@Override
	public AST visitAND(implParser.ANDContext ctx) {
		return new AND((Expr)visit(ctx.e1),(Expr)visit(ctx.e2));
	}

	@Override
	public AST visitParentheses(implParser.ParenthesesContext ctx) {
		return visit(ctx.e1);
	}

	@Override
	public AST visitStringVar(implParser.StringVarContext ctx) {
		return null;
	}

 */
}

